version: '3'

services:
    ubuntu:
        container_name: ubuntu
        build :
            context : ./ubuntu
            dockerfile : Dockerfile
            args: 
                USER_NAME: $USER_NAME
                USER_ID: $USER_ID
                GROUP_ID: $GROUP_ID

        volumes:
            - ./workspace:/home/$USER_NAME/workspace
        tty: true